version: '3'
services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 5000
      EMAIL_HOST: # insert yours
      EMAIL_PASSWORD: # insert yours
    ports:
      - "5000:5000"
    
  client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
 